# Generated by Django 3.2.6 on 2022-04-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(default='no name', max_length=400)),
                ('medida', models.CharField(default='sin medida', max_length=400)),
                ('precio', models.CharField(default='sin precio', max_length=400)),
            ],
            options={
                'verbose_name_plural': 'productos',
                'db_table': 'producto',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='producto',
            index=models.Index(fields=['id_producto'], name='producto_id_prod_6899fc_idx'),
        ),
    ]
