# Generated by Django 3.2.6 on 2022-11-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='no name', max_length=400, unique=True),
        ),
    ]
